### ISSUE TITLE
Share artifacts on HF

### ISSUE THREAD

**Issue by NielsRogge** [maeyounes/SparseCraft#1]
Hi there,

Congrats on your work! Niels here from the open-source team at Hugging Face. I discovered your work through the paper page: https://huggingface.co/papers/2407.14257 (feel free to claim it if you have a HF account).

I was wondering whether you would be up for making your dataset available on the hub, such that people can do:

```python
from datasets import load_dataset

dataset = load_dataset("your-hf-username/sparsecraft")
```

? This would also ensure a dataset viewer, which allows people to easily discover and read the first few rows of the dataset in the browser, along with tags like "image-to-3D" so that people can easily find it when filtering hf.co/datasets (filters are on the left).

See here for a guide: https://huggingface.co/docs/datasets/loading.

It could then also be linked to the paper page, as explained here: https://huggingface.co/docs/hub/en/datasets-cards#linking-a-paper.

Let me know if you need any help!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by maeyounes** [comment]
Hello there,

Thank you for the interest. I will gladly do this when I upload the dataset.

Regards,

MY
